<?php

namespace ContainerTkObAdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RU9gbyCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RU9gbyC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RU9gbyC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'terrarium' => ['privates', '.errored..service_locator.RU9gbyC.App\\Entity\\Terrarium', NULL, 'Cannot autowire service ".service_locator.RU9gbyC": it needs an instance of "App\\Entity\\Terrarium" but this type has been excluded in "config/services.yaml".'],
            'terrariumRepository' => ['privates', 'App\\Repository\\TerrariumRepository', 'getTerrariumRepositoryService', true],
        ], [
            'terrarium' => 'App\\Entity\\Terrarium',
            'terrariumRepository' => 'App\\Repository\\TerrariumRepository',
        ]);
    }
}
