<?php

namespace ContainerTkObAdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IrUZOHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ir_uZOH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ir_uZOH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'humidityRepository' => ['privates', 'App\\Repository\\HumidityRepository', 'getHumidityRepositoryService', true],
        ], [
            'humidityRepository' => 'App\\Repository\\HumidityRepository',
        ]);
    }
}
