<?php

namespace ContainerTkObAdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MIwn17TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mIwn17T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mIwn17T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'humidity' => ['privates', '.errored..service_locator.mIwn17T.App\\Entity\\Humidity', NULL, 'Cannot autowire service ".service_locator.mIwn17T": it needs an instance of "App\\Entity\\Humidity" but this type has been excluded in "config/services.yaml".'],
        ], [
            'humidity' => 'App\\Entity\\Humidity',
        ]);
    }
}
