<?php

namespace ContainerTkObAdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BPDHAvmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bPDHAvm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bPDHAvm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'terrarium' => ['privates', '.errored..service_locator.bPDHAvm.App\\Entity\\Terrarium', NULL, 'Cannot autowire service ".service_locator.bPDHAvm": it needs an instance of "App\\Entity\\Terrarium" but this type has been excluded in "config/services.yaml".'],
        ], [
            'terrarium' => 'App\\Entity\\Terrarium',
        ]);
    }
}
