<?php

namespace ContainerTkObAdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MJm4rmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m_Jm4rm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m_Jm4rm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'humidity' => ['privates', '.errored..service_locator.m_Jm4rm.App\\Entity\\Humidity', NULL, 'Cannot autowire service ".service_locator.m_Jm4rm": it needs an instance of "App\\Entity\\Humidity" but this type has been excluded in "config/services.yaml".'],
            'humidityRepository' => ['privates', 'App\\Repository\\HumidityRepository', 'getHumidityRepositoryService', true],
        ], [
            'humidity' => 'App\\Entity\\Humidity',
            'humidityRepository' => 'App\\Repository\\HumidityRepository',
        ]);
    }
}
