<?php

namespace ContainerTkObAdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHumidity2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.m_Jm4rm.App\Entity\Humidity' shared service.
     *
     * @return \App\Entity\Humidity
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.m_Jm4rm": it needs an instance of "App\\Entity\\Humidity" but this type has been excluded in "config/services.yaml".');
    }
}
