<?php

namespace ContainerTkObAdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemperatureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TZZtJ9x.App\Entity\Temperature' shared service.
     *
     * @return \App\Entity\Temperature
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.TZZtJ9x": it needs an instance of "App\\Entity\\Temperature" but this type has been excluded in "config/services.yaml".');
    }
}
