<?php

namespace ContainerTkObAdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTerrarium2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bPDHAvm.App\Entity\Terrarium' shared service.
     *
     * @return \App\Entity\Terrarium
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bPDHAvm": it needs an instance of "App\\Entity\\Terrarium" but this type has been excluded in "config/services.yaml".');
    }
}
