<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Humidity extends \App\Entity\Humidity implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'App\\Entity\\Data'."\0".'delta' => ['App\\Entity\\Data', 'delta', null],
        "\0".'App\\Entity\\Data'."\0".'nightValue' => ['App\\Entity\\Data', 'nightValue', null],
        "\0".'App\\Entity\\Data'."\0".'value' => ['App\\Entity\\Data', 'value', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'delta' => ['App\\Entity\\Data', 'delta', null],
        'id' => [parent::class, 'id', null],
        'nightValue' => ['App\\Entity\\Data', 'nightValue', null],
        'value' => ['App\\Entity\\Data', 'value', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
