<?php

namespace ContainerUPlCfwf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JQSOeJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JQSOeJ_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JQSOeJ_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.UUMJOv4', 'get_ServiceLocator_UUMJOv4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\TerrariumController::delete' => ['privates', '.service_locator.RU9gbyC', 'get_ServiceLocator_RU9gbyCService', true],
            'App\\Controller\\TerrariumController::edit' => ['privates', '.service_locator.RU9gbyC', 'get_ServiceLocator_RU9gbyCService', true],
            'App\\Controller\\TerrariumController::index' => ['privates', '.service_locator.pPXPJTZ', 'get_ServiceLocator_PPXPJTZService', true],
            'App\\Controller\\TerrariumController::new' => ['privates', '.service_locator.pPXPJTZ', 'get_ServiceLocator_PPXPJTZService', true],
            'App\\Controller\\TerrariumController::show' => ['privates', '.service_locator.bPDHAvm', 'get_ServiceLocator_BPDHAvmService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.UUMJOv4', 'get_ServiceLocator_UUMJOv4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\TerrariumController:delete' => ['privates', '.service_locator.RU9gbyC', 'get_ServiceLocator_RU9gbyCService', true],
            'App\\Controller\\TerrariumController:edit' => ['privates', '.service_locator.RU9gbyC', 'get_ServiceLocator_RU9gbyCService', true],
            'App\\Controller\\TerrariumController:index' => ['privates', '.service_locator.pPXPJTZ', 'get_ServiceLocator_PPXPJTZService', true],
            'App\\Controller\\TerrariumController:new' => ['privates', '.service_locator.pPXPJTZ', 'get_ServiceLocator_PPXPJTZService', true],
            'App\\Controller\\TerrariumController:show' => ['privates', '.service_locator.bPDHAvm', 'get_ServiceLocator_BPDHAvmService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TerrariumController::delete' => '?',
            'App\\Controller\\TerrariumController::edit' => '?',
            'App\\Controller\\TerrariumController::index' => '?',
            'App\\Controller\\TerrariumController::new' => '?',
            'App\\Controller\\TerrariumController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TerrariumController:delete' => '?',
            'App\\Controller\\TerrariumController:edit' => '?',
            'App\\Controller\\TerrariumController:index' => '?',
            'App\\Controller\\TerrariumController:new' => '?',
            'App\\Controller\\TerrariumController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
