<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSnZbpng\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSnZbpng/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSnZbpng.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSnZbpng\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSnZbpng\App_KernelDevDebugContainer([
    'container.build_hash' => 'SnZbpng',
    'container.build_id' => '6292ad2a',
    'container.build_time' => 1675156023,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSnZbpng');
