<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTkObAdq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTkObAdq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTkObAdq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTkObAdq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTkObAdq\App_KernelDevDebugContainer([
    'container.build_hash' => 'TkObAdq',
    'container.build_id' => '45699758',
    'container.build_time' => 1675883584,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTkObAdq');
